//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDLUsingAJAX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public Nullable<int> State_id { get; set; }
        public int City_id { get; set; }
        public string City_name { get; set; }
    
        public virtual State State { get; set; }
    }
}
